Repository streamlit/docs, pull requests merged in 2022-09, with the labels that each got.

#474 Update aws-s3.md with AWS_DEFAULT_REGION
  content/kb/tutorials/databases/aws-s3.md
  public/images/databases/aws-3.png
Labels: waiting on user response

#486 Add examples of replaying static `st` elements in cache-decorated functions
  content/library/api/performance/experimental-memo.md
  content/library/api/performance/experimental-singleton.md
  public/images/cached-st-function-warning-singleton.png
  public/images/cached-st-function-warning.png
  public/images/replay-cached-elements-singleton.png
  public/images/replay-cached-elements.png
Labels: documentation

#485 Fix styling of inline code in headings
  components/utilities/headerLink.js
  public/sitemap.xml
Labels: bug, design

#491 Fix styling on `token.decorator.annotation.punctuation`
  components/blocks/code.module.css
Labels: bug, design

#493 Style inline code in callouts like inline code in paragraphs
  components/blocks/callout.module.css
Labels: design
